# Jekyll configuration
title: Prix Carburants
author: Antoine Mandin
email: doreapp.contact@gmail.com
description: >-
  Statistiques sur les prix des carburants français

plugins:
- jekyll-seo-tag

github_username: Doreapp
github_repo: https://github.com/Doreapp/prix-carburants

theme: jekyll-theme-cayman
url: https://doreapp.github.io/prix-carburants/
repository: Doreapp/prix-carburants
