# Jekyll configuration

title: Prix Carburants
email: doreapp.contact@gmail.com
description: >-
  [EN] A website to display statistics and raw information about french fuel prices.
  [FR] Un site pour afficher des statistiques et informations sur les prix des carburants.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
github_username:  doreapp
github_repo: https://github.com/Doreapp/prix-carburants

# Build settings
theme: jekyll-theme-yat
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
