# Jekyll configuration
remote_theme: pages-themes/cayman

title: Prix Carburants
author: Antoine Mandin
email: doreapp.contact@gmail.com
description: >-
  Statistiques sur les prix des carburants français

plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-remote-theme

github_username: Doreapp
github_repo: https://github.com/Doreapp/prix-carburants

baseurl: ""
url: https://doreapp.github.io/prix-carburants/
repository: Doreapp/prix-carburants
