# Wrokflow to deploy GitHub-pages website (in gh-pages)
name: Deploy

on: [push]
#  push:
#    paths:
#      - 'gh-pages/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Send files to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch
        mv --force gh-pages/* .
        git add *
        git stash
        git checkout gh-pages
        git stash pop
        if test -n "$( git status -s)"; then
          echo "machine github.com login $GITHUB_ACTOR password $GITHUB_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git config user.name "$GITHUB_ACTOR"
          git config user.email "doreapp@users.noreply.github.com"
          git diff
          git commit -m "🚀 Deploy GitHub pages"
          git push
          echo "GitHub pages sources updated"
        else
          echo "No file to update"
        fi
