# Main Continuous integration workflow
name: Continuous Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Linter analysis
      run: |
        make lint
    - name: Update data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch
        make update-data
        git add data/
        git stash
        git checkout test
        git stash pop
        git status --porcelain
        if test -n "$( git status -s)"; then
          echo "machine github.com login $GITHUB_ACTOR password $GITHUB_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc
          git config user.name "$GITHUB_ACTOR"
          git config user.email "doreapp@users.noreply.github.com"
          git diff
          git commit -m "⬆️ Update data"
          git push
          echo "Data pushed to data branch"
        else
          echo "No data to update"
        fi
